version: '3.8'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Kutty#33#
      MYSQL_DATABASE: miniproject
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  ml_service:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5000:5000"

  server:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Kutty#33#
      DB_NAME: miniproject
    depends_on:
      mysql:
        condition: service_healthy
      ml_service:
        condition: service_started
